package com.kafka.producer.agentic;

public enum FailureClass {
    PASSED,
    AUTHORIZATION_FAILURE,
    PLANNER_FAILURE,
    POLICY_REJECTION,
    INJECTION_FAILURE,
    HARNESS_FAILURE,
    PRODUCER_CORRECTNESS_FAILURE,
    PRODUCER_SAFETY_FAILURE,
    PRODUCER_RECOVERY_FAILURE,
    CLEANUP_FAILURE
}
